### PR TITLE
Added two Euclid ERO images

### PR DESCRIPTION
**Pull request by astrodavid10**
NGC 6822 and IC 342 added to Constellations

### CODE REVIEW

**Comment by pkgw** [comment]
These look great!

**Comment by alexanderbock** [comment]
Yea, I agree!  Did these get added to any catalog as well?  I can't find them in our list of collections

```
<Folder Name="Collections" Group="Explorer">
<Folder Name="All-Sky Surveys" Url="http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=surveys" Group="Explorer" Thumbnail="http://www.worldwidetelescope.org/wwtweb/thumbnail.aspx?name=aitoff"/>
<Folder Name="HiPS Surveys" Url="http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=hips" Group="Explorer" Thumbnail="http://www.worldwidetelescope.org/wwtweb/thumbnail.aspx?name=aitoff"/>
<Folder Name="Spitzer Studies" Url="http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=studiesspitzer" Group="Explorer" Searchable="True" Type="Sky" Thumbnail="http://www.worldwidetelescope.org/wwtweb/thumbnail.aspx?name=spitzer"/>
<Folder Name="Chandra Studies" Url="http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=studieschandra" Group="Explorer" Searchable="True" Type="Sky" Thumbnail="http://www.worldwidetelescope.org/wwtweb/thumbnail.aspx?name=chandra"/>
<Folder Name="Hubble Studies" Url="http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=studieshubble" Group="Explorer" Searchable="True" Type="Sky" Thumbnail="http://www.worldwidetelescope.org/wwtweb/thumbnail.aspx?name=hubble"/>
<Folder Name="Astrophotography" Url="http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=astrophoto" Group="Explorer" Searchable="True" Type="Sky" Thumbnail="http://www.worldwidetelescope.org/wwtweb/thumbnail.aspx?name=egastrophoto"/>
<Folder Name="SOFIA Studies" Url="http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=sofia_studies" Group="Explorer" Searchable="True" Type="Sky" Thumbnail="http://www.worldwidetelescope.org/wwtweb/thumbnail.aspx?name=nasa_sofia"/>
<Folder Name="Radio Studies" Url="http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=studiesradio" Group="Explorer" Searchable="True" Type="Sky" Thumbnail="http://www.worldwidetelescope.org/wwtweb/thumbnail.aspx?name=radiostudies"/>
<Folder Name="NOAO Studies" Url="http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=studiesnoao" Group="Explorer" Searchable="True" Type="Sky" Thumbnail="http://www.worldwidetelescope.org/wwtweb/thumbnail.aspx?name=noao"/>
<Folder Name="Gemini Studies" Url="http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=geministudies" Group="Explorer" Searchable="True" Type="Sky" Thumbnail="http://www.worldwidetelescope.org/wwtweb/thumbnail.aspx?name=geminiobservatory"/>
<Folder Name="JWST" Url="http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=jwst" Group="JWST" Thumbnail="http://www.worldwidetelescope.org/wwtweb/thumbnail.aspx?name=jwst"/>
<Folder Name="European Southern Observatory (ESO)" Url="http://www.worldwidetelescope.org/wwtweb/catalog.aspx?W=eso" Group="Explorer" Searchable="True" Thumbnail="http://www.worldwidetelescope.org/wwtweb/thumbnail.aspx?name=jwst"/>
</Folder>
```

**Comment by alexanderbock** [comment]
Yea, we did set up our own (https://data.openspaceproject.com/wwt/1/imagecollection.wtml). The original reason was to remove the panorama ones. Would love to just refer to your collections as much as possible to prevent duplicate work and prevent mistakes, ofc, but I can add them to our collection for the time being.

Thanks!

**Comment by pkgw** [comment]
Yeah, there's always a tradeoff with this sort of thing. @astrodavid10 do you have any opinions about integrating Euclid images into the Windows/webclient folder hierarchy? To add a new folder we'd just have to decide where to file it and create a little thumbnail image.

**Pull request merged**
